name = "MQTT"
uuid = "ebefff21-3b8f-497c-a71a-d17835ab79ba"
authors = ["Nicholas Shindler <nick@shindler.tech> and contributors"]
version = "0.1.0"

[deps]

[weakdeps]
AWSCRT = "df31ea59-17a4-4ebd-9d69-4f45266dc2c7"
MQTTClient = "985f35cc-2c3d-4943-b8c1-f0931d5f0959"

[extensions]
AWSCRTExt = "AWSCRT"
MQTTClientExt = "MQTTClient"

[compat]
julia = "1.9"
MQTTClient = "^0.3.1"
AWSCRT = "^0.3"
Aqua = "^0.8"
Test = "^0"

[extras]
AWSCRT = "df31ea59-17a4-4ebd-9d69-4f45266dc2c7"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
MQTTClient = "985f35cc-2c3d-4943-b8c1-f0931d5f0959"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "AWSCRT", "MQTTClient", "Test"]
