name = "MQTT"
uuid = "ebefff21-3b8f-497c-a71a-d17835ab79ba"
authors = ["Nicholas Shindler <nick@shindler.tech> and contributors"]
version = "0.0.1-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
